services:
  - type: web
    name: mini-market-backend
    runtime: docker
    rootDir: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: FRONTEND_URLS
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: FILESYSTEM_DISK
        value: public
      - key: RUN_MIGRATIONS
        value: "true"
